# This tells Gitpod which Docker image to use for your workspace.
# The 'workspace-full' image is a large, stable image with Node.js, Docker, and many other tools pre-installed.
image: gitpod/workspace-full

tasks:
  - name: Setup & Instructions
    # This command will run once when the workspace starts.
    # It prints out the manual setup steps for you to follow.
    command: |
      echo 'Your Gitpod environment is ready.'
      echo 'Please run the following commands one by one in this terminal:'
      echo '1. npm install'
      echo '2. curl -L "https://github.com/hyperledger/fabric/releases/download/v2.2.0/hyperledger-fabric-linux-amd64-2.2.0.tar.gz" | tar xz'
      echo '3. bash ./scripts/generate-artifacts.sh'
      echo '4. docker-compose up -d --build'
      echo '5. sleep 30'
      echo '6. docker exec cli bash scripts/setup-channel.sh'
      echo '7. curl -X POST http://localhost:3000/api/connect-blockchain'
